export const ADD_GOOD = 'ADD_GOOD';
export const REMOVE_GOOD = 'REMOVE_GOOD';
export const GET_GOOD_DETAILS = 'GET_GOOD_DETAILS';

export const FETCH_GOODS_REQUEST = 'FETCH_GOODS_REQUEST';
export const FETCH_GOODS_SUCCESS = 'FETCH_GOODS_SUCCESS';
export const FETCH_GOODS_FAILURE = 'FETCH_GOODS_FAILURE';
